---
# batch : directories
- name: "Create directory : {{ version_directory }}/{{ batch.name }}/{{ batch_bin_directory }}"
  file:
    path: "{{ version_directory }}/{{ batch.name }}/{{ batch_bin_directory }}"
    state: directory

- name: "Create directory : {{ version_directory }}/{{ batch.name }}/{{ batch_logs_directory }}"
  file:
    path: "{{ version_directory }}/{{ batch.name }}/{{ batch_logs_directory }}"
    state: directory

- name: "Create directory : {{ version_directory }}/{{ batch.name }}/{{ batch_script_directory }}"
  file:
    path: "{{ version_directory }}/{{ batch.name }}/{{ batch_script_directory }}"
    state: directory
  when: batch.script

# batch : jar
- name: "Copy jar file for batch : {{ batch.name }}"
  copy:
    src: "{{ work_directory }}/{{ batch_file | regex_replace(batch_name_template, batch.name) }}"
    dest: "{{ version_directory }}/{{ batch.name }}/{{ batch_bin_directory }}/{{ batch.name }}.jar"
    remote_src: yes
    mode: 0755

# batch : script
- name: "Copy script file for batch : {{ batch.name }}"
  unarchive:
    src: "{{ work_directory }}/{{ batch_script_file | regex_replace(batch_name_template, batch.name) }}"
    dest: "{{ version_directory }}/{{ batch.name }}/{{ batch_script_directory }}/"
    remote_src: yes
    mode: 0755
  when: batch.script
...